name: poliservis-gr06
version: '3.8'

services:

  app:
    image: jimmynow/uniservicios:latest
    container_name: poliservis-app
    ports:
      - "8085:8080"
    environment:
      MYSQL_HOST: poli-servis-jimmyarias772.g.aivencloud.com
      MYSQL_PORT: 13512
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: avnadmin
      MYSQL_PASSWORD: AVNS_z0fh2LSeHStzFyIugpo
    networks:
      - poliservis-net

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jimmynow/uniservicios-jenkins:latest
    container_name: poliservis-jenkins
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - poliservis-net
    restart: unless-stopped

networks:
  poliservis-net:
    driver: bridge
